site_name: BSPLib
site_url: https://www.bsplib.eu
repo_url: https://github.com/Zefiros-Software/BSPLib
site_description: BSPLib a fast and easy to use parallel computation libary.
theme: readthedocs
copyright: Copyright (c) 2015 Mick van Duijn, Koen Visscher and Paul Visscher