site_name: BSPLib
site_url: https://www.bsplib.eu
repo_url: https://github.com/Zefiros-Software/BSPLib
site_description: BSPLib a fast and easy to use parallel computation libary.
theme: readthedocs
copyright: Copyright (c) 2015 Mick van Duijn, Koen Visscher and Paul Visscher

pages:
- BSP: 'index.md'
- Program Logic: 
    - 'Execute': 'logic/execute.md'
    - 'Init': 'logic/init.md'
    - 'Begin': 'logic/begin.md'
    - 'End': 'logic/end.md'
- Utilities:
    - 'NProcs': 'util/nprocs.md'
    - 'ProcId': 'util/procid.md'
    - 'Time': 'util/time.md'
- Halting:
    - 'Abort': 'halting/abort.md'
- Synchronisation Point:
    - 'Sync': 'sync/sync.md'
- Registration & Deregistration:
    - 'Put': 'regdereg/push.md'
    - 'Pop': 'regdereg/pop.md'
- Communication: 'communication.md'
- Messaging: 'messaging.md'
- Messaging Utilities: 'messagingutil.md'
- High Performance: 'hp.md'
- Classic: 'classic.md'